version: "3.9"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    volumes:
      - ./dump/fiftyville.sql:/dump.sql
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d fiftyville" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - api-network

  api:
    build: .
    environment:
      - DB_HOST=$DB_HOST
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - api-network
    restart: always

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - api-network
    restart: always


networks:
  api-network:
    driver: bridge
