services:
  api:
    build: .
    networks:
      - api-network

  proxy:
    image: nginx
    restart: always
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - api-network

networks:
  api-network:
    driver: bridge
