version: "3.9"

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=fiftyville
    volumes:
      - ./dump/fiftyville.sql:/dump.sql
      - ./scripts/initdb.sh:/docker-entrypoint-initdb.d/initdb.sh
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d fiftyville" ]
      interval: 3s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - api-network

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: fiftyville
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - api-network

  proxy:
    image: nginx
    volumes:
      - type: bind
        source: ./proxy/nginx.conf
        target: /etc/nginx/conf.d/default.conf
        read_only: true
    ports:
      - 80:80
    depends_on:
      - api
    networks:
      - api-network
    restart: always


networks:
  api-network:
    driver: bridge
