openapi: 3.1.0
info:
  title: Gofiftyville API
  description: Fiftyville API written in Go.
  version: 1.0.0
  contact:
    url: https://gofityville.com/api/v1
  x-logo:
    url: https://raw.githubusercontent.com/seyLu/gofiftyville/main/detective-golang.svg
    altText: Gofiftyville Logo
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: https://gofityville.com/api/v1
paths:
  /crime-scene-reports:
    $ref: paths/crime-scene-reports.yml
  /interviews:
    $ref: paths/interviews.yml
  /bakery-security-logs:
    $ref: paths/bakery-security-logs.yml
  /atm-transactions:
    $ref: paths/atm-transactions.yml
  /people:
    $ref: paths/people.yml
  /phone-calls:
    $ref: paths/phone-calls.yml
  /flights:
    $ref: paths/flights.yml
  /airports:
    $ref: paths/airports.yml
  /final-answer:
    $ref: paths/final-answer.yml
