name: Test
run-name: Testing ${{ github.repository }}

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Perform test
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go-version: ["1.23"]

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@951b48540b429070694bc8abd82fd6901eb123ca # v2.9.1
        with:
          egress-policy: audit

      - name: Checkout repository
        uses: actions/checkout@9a9194f87191a7e9055e3e9b95b8cfb13023bb08 # v4.1.7

      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@b26d40294f8ad76fcc90b915dac85892322fe62d # v5.0.2
        with:
          go-version: ${{ matrix.go-version }}

      - name: Go Test
        run: go test -failfast ./...
